from setuptools import setup, find_packages

setup(
    name="qtrust",
    version="0.1.0",
    description="QTrust - Deep Reinforcement Learning based Blockchain Sharding System",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="AI Research Team",
    author_email="research@example.com",
    url="https://github.com/example/qtrust",
    packages=find_packages(),
    install_requires=[
        "torch>=1.10.0",
        "numpy>=1.19.0",
        "pandas>=1.3.0",
        "matplotlib>=3.4.0",
        "tensorflow>=2.7.0",
        "tensorflow-federated==0.20.0",
        "jaxlib~=0.1.76",
        "gym>=0.21.0",
        "networkx>=2.6.0",
        "tqdm>=4.62.0",
        "scikit-learn>=1.0.0",
        "seaborn>=0.11.0",
        "pytest>=6.2.5",
        "wandb>=0.12.0",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
    ],
    keywords="blockchain, deep-learning, reinforcement-learning, sharding, dqn",
    python_requires=">=3.8",
    include_package_data=True,
    entry_points={
        "console_scripts": [
            "qtrust-simulation=main:main",
        ],
    },
)
